# ■第2週_授業前課題3_行列積のスクラッチ

## 【問題1】行列積を手計算する

▼1行目の左
　　　　→-1*0+2*0+3*2=6
 ▼1行目真ん中
　　　 → -1*2+2*2+3*9=29
 ▼1行目右
 　　　→　-1*1+ 2*(-8)+3*(-1)=20
    
 ▼2行目左
 　　　→4*0+(-5)*0+6*2 =12
 ▼2行目真ん中
 　　→4*2+(-5)*2+6*9=52
 ▼2行目右
 　　→4*1+(-5)*(-8)+6*(-1)=38
   
  ▼3行目左
  　　→7*0+8*0+(-9)*2=18
  ▼3行目真ん中
  　　→7*2+8*2+(-9)*9=-51
   ▼3行目右
   　→7*1+8*(-8)+(-9)*(-1)=-48
   

## 【問題2】Numpyの関数による計算

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装

In [17]:
#nampy配列に入れて要素を足していきshapeで最後に形を整える
import numpy as np
temporary_ndarray=np.array([1,5])
kon = np.append(temporary_ndarray, np.array([3,4]))
kon

array([1, 5, 3, 4])

In [295]:
temporary_ndarray=np.array([])
one_left = a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0]
temporary_ndarray=np.append(temporary_ndarray, np.array([one_left]))
one_center =  a_ndarray[0][0]*b_ndarray[0][1]+a_ndarray[0][1]*b_ndarray[1][1]+a_ndarray[0][2]*b_ndarray[2][1]
temporary_ndarray=np.append(temporary_ndarray, np.array([one_center]))
one_right =  a_ndarray[0][0]*b_ndarray[0][2]+a_ndarray[0][1]*b_ndarray[1][2]+a_ndarray[0][2]*b_ndarray[2][2]
temporary_ndarray=np.append(temporary_ndarray, np.array([one_right]))

two_left = a_ndarray[1][0]*b_ndarray[0][0]+a_ndarray[1][1]*b_ndarray[1][0]+a_ndarray[1][2]*b_ndarray[2][0]
temporary_ndarray=np.append(temporary_ndarray, np.array([two_left]))
two_center =  a_ndarray[1][0]*b_ndarray[0][1]+a_ndarray[1][1]*b_ndarray[1][1]+a_ndarray[1][2]*b_ndarray[2][1]
temporary_ndarray=np.append(temporary_ndarray, np.array([two_center]))
two_right =  a_ndarray[1][0]*b_ndarray[0][2]+a_ndarray[1][1]*b_ndarray[1][2]+a_ndarray[1][2]*b_ndarray[2][2]
temporary_ndarray=np.append(temporary_ndarray, np.array([two_right]))

three_left = a_ndarray[2][0]*b_ndarray[0][0]+a_ndarray[2][1]*b_ndarray[1][0]+a_ndarray[2][2]*b_ndarray[2][0]
temporary_ndarray=np.append(temporary_ndarray, np.array([three_left]))
three_center =  a_ndarray[2][0]*b_ndarray[0][1]+a_ndarray[2][1]*b_ndarray[1][1]+a_ndarray[2][2]*b_ndarray[2][1]
temporary_ndarray=np.append(temporary_ndarray, np.array([three_center]))
three_right =  a_ndarray[2][0]*b_ndarray[0][2]+a_ndarray[2][1]*b_ndarray[1][2]+a_ndarray[2][2]*b_ndarray[2][2]
temporary_ndarray=np.append(temporary_ndarray, np.array([three_right]))

temporary_ndarray.reshape(3,3)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題4】行列積を行う関数の作成

### 下記は動かないなぜ駄目なのか教えて頂きたいです。np.appendがが上手く機能していな買ったです

In [364]:
#def calculation(arrayA,arrayB):
arrayA = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
arrayB = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

line_number = arrayA.shape[0]
row_number = arrayB.shape[1]

temp_array = np.array([])

for i in range(3):
    for j in range(3):
        cul = np.sum(arrayA[i]*arrayB[:,j])
        np.append(temp_array,cul)
print(temp_array)


[]


### こちらが提出用のよう解答です。リストを利用

In [367]:
def calculation(arrayA,arrayB):
    line_number = arrayA.shape[0]
    row_number = arrayB.shape[1]

    temp_array = []

    for i in range(line_number):
        for j in range(row_number):
            cul = sum(arrayA[i]*arrayB[:,j])
            temp_array.append(cul)
    return np.reshape(temp_array,(line_number, row_number))

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

calculation(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題5】計算が定義されない入力を判定する

In [381]:
'''
■補足説明
A行列×B行列とすると計算できないのはA行列の列数とB行列の行数が一致しない時
'''
def calculation2(arrayA,arrayB):
    line_number = arrayA.shape[0]
    row_number = arrayB.shape[1]
    error = "入力値では計算できないです。入力されるA行列の列数とB行列の行数を揃えてください。"
    if line_number != row_number:
        return error
    else:
        temp_array = []
        for i in range(line_number):
            for j in range(row_number):
                cul = sum(arrayA[i]*arrayB[:,j])
                temp_array.append(cul)
        return np.reshape(temp_array,(line_number, row_number))
    
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

calculation2(d_ndarray,e_ndarray)

'入力値では計算できないです。入力されるA行列の列数とB行列の行数を揃えてください。'

## 【問題6】転置

In [384]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

'''
■補足
b_ndarray行列を転置して計算する
'''
new_b_ndarray = b_ndarray.T
calculation2(a_ndarray,new_b_ndarray)

array([[  7, -20,  13],
       [ -4, -58, -43],
       [  7,  88,  95]])